using Broiler.Dom;
using Broiler.HtmlBridge.Dom.Runtime;
using Broiler.HtmlBridge.Jseal;
using Broiler.JavaScript.Engine;
using Broiler.JavaScript.Runtime;

namespace Broiler.HtmlBridge;

/// <summary>
/// Registers the Custom Elements surface: the <c>CustomElementRegistry</c> interface, the
/// <c>customElements</c> instance, the constructible <c>HTMLElement</c> base, and the subscription
/// that turns canonical DOM mutations into reaction callbacks.
/// </summary>
public sealed partial class DomBridge
{
    private Dom.Features.CustomElementsBinding? _customElements;

    internal Dom.Features.CustomElementsBinding CustomElements =>
        _customElements ??= new Dom.Features.CustomElementsBinding(this);

    /// <summary>
    /// Replaces the non-constructible <c>HTMLElement</c> with the base a custom element extends, and
    /// installs the registry.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The base is JavaScript for one reason: it needs <c>new.target</c>. <c>new X()</c> runs
    /// <c>X</c>'s constructor, which calls <c>super()</c>, and only <c>new.target</c> says which
    /// subclass is being constructed — so which prototype the element must get and, through the
    /// registry, which tag name it has. The base reads it there and calls the host for the element
    /// itself.
    /// </para>
    /// <para>
    /// <b>The base stays JavaScript even though <see cref="JsCall.NewTarget"/> now exists.</b> A host
    /// constructor built with <c>NewConstructor</c> does receive <c>new.target</c>, so this one shim
    /// could move — but it is not the only caller of the host hook below. Every per-tag interface
    /// constructor calls it too, and those are generated by <c>DomBridge/Utilities.DomInterfaces.cs</c>
    /// in exactly this <c>(new.target, interfaceName)</c> shape. The hook is one function serving both,
    /// so the argument convention is one decision; moving half of it would leave the host reading a
    /// call frame that belongs to the ordinary call the shim makes rather than to the <c>new</c> that
    /// began it, which is a different value. It moves when that file does.
    /// </para>
    /// <para>
    /// Returning an object from a base constructor is what makes this work: <c>super()</c>'s result
    /// becomes <c>this</c>, so the subclass constructor goes on to run against a real DOM element.
    /// The element's members are its own properties, so re-pointing its prototype at
    /// <c>new.target.prototype</c> adds the class's methods without displacing any of them, and the
    /// class chain already ends at <c>HTMLElement.prototype</c> — which is genuinely in the element's
    /// chain since the interface prototypes were linked.
    /// </para>
    /// <para>
    /// <b>The JavaScript below is host script</b> — authored in this repository and shipped with it —
    /// so it runs through <see cref="IJsSource.EvaluateHostScript"/> rather than the guest-source entry
    /// point, and the page's Content-Security-Policy has no say over it.
    /// </para>
    /// </remarks>
    /// <param name="context">
    /// The engine context the unmigrated caller (<c>DomBridge/Registration/Registration.cs</c>) still
    /// holds. Nothing here reads it: this pass works through <see cref="Realm"/>, which is the same
    /// realm. The parameter stays only so that call site needs no edit while it is another group's
    /// file.
    /// </param>
    /// <param name="window">
    /// The window object <c>customElements</c> is installed on. Under this engine it is the global
    /// itself, but it is taken rather than derived so this pass installs on the same object the
    /// registration hub built everything else on.
    /// </param>
    private void RegisterCustomElements(JSContext context, JSObject window)
    {
        var realm = Realm;

        var registry = realm.NewObject();
        realm.DefineValue(registry, "define",
            realm.NewMethod("define", (in call) => CustomElements.Define(in call), 2));
        realm.DefineValue(registry, "get",
            realm.NewMethod("get", (in call) => CustomElements.Get(in call), 1));
        realm.DefineValue(registry, "getName",
            realm.NewMethod("getName", (in call) => CustomElements.GetName(in call), 1));
        realm.DefineValue(registry, "whenDefined",
            realm.NewMethod("whenDefined", (in call) => CustomElements.WhenDefined(in call), 1));
        realm.DefineValue(registry, "upgrade",
            realm.NewMethod("upgrade", (in call) => CustomElements.Upgrade(in call), 1));

        // The host half of the base, reached only from the JavaScript below and from the per-tag
        // interface constructors. Named with the bridge's reserved prefix and deleted from the global
        // once the base has closed over it, so a page cannot call it and mint an element out of band.
        realm.SetProperty(realm.Global, "__broilerConstructCustomElement",
            realm.NewMethod("constructCustomElement", (in call) => CustomElements.ConstructForNewTarget(in call), 2));
        realm.SetProperty(realm.Global, "__broilerCustomElementRegistry", registry);

        realm.EvaluateHostScript("""
            (function () {
                var construct = __broilerConstructCustomElement;
                var registry = __broilerCustomElementRegistry;

                // The per-tag interface globals were registered before this pass and left their
                // construction hook unbound, because constructing is this registry's job: a
                // customized built-in reaches HTMLButtonElement (or whichever) through super(), and
                // the element it must produce is one of ours. Binding it here, once, is what makes
                // `class Fancy extends HTMLButtonElement` work; the setter deletes itself.
                if (typeof __broilerBindInterfaceConstructor === 'function')
                    __broilerBindInterfaceConstructor(construct);

                // The custom element base. Replaces the illegal-constructor HTMLElement, which is
                // still what a bare `new HTMLElement()` gets: without a new.target there is no
                // subclass to build, and the host answers that with a TypeError.
                function HTMLElement() {
                    var target = new.target;
                    if (!target) throw new TypeError('Illegal constructor');
                    // The host answers null for a new.target with no definition — a bare
                    // `new HTMLElement()`, whose new.target is HTMLElement itself, and any subclass
                    // that was never registered — and a string when the definition exists but names
                    // a different interface, which is a customized built-in reached through
                    // HTMLElement. Throwing here rather than there is what makes either a real
                    // TypeError with a name and a message: a host throw would surface as a bare
                    // string with neither.
                    var element = construct(target, 'HTMLElement');
                    if (typeof element === 'string') throw new TypeError(element);
                    if (!element) throw new TypeError('Illegal constructor');
                    // The element carries its DOM members as own properties, so re-pointing the
                    // prototype adds the class without taking anything away.
                    Object.setPrototypeOf(element, target.prototype);
                    return element;
                }

                // Keep the prototype the interface linking already built, so the element's chain
                // still reaches Element, Node and EventTarget through it and every wrapper linked to
                // HTMLElement.prototype keeps the object it was linked to.
                HTMLElement.prototype = __broilerHTMLElementPrototype;
                Object.defineProperty(HTMLElement.prototype, 'constructor', {
                    value: HTMLElement, writable: true, enumerable: false, configurable: true
                });
                globalThis.HTMLElement = HTMLElement;

                function CustomElementRegistry() { throw new TypeError('Illegal constructor'); }
                globalThis.CustomElementRegistry = CustomElementRegistry;
                Object.setPrototypeOf(registry, CustomElementRegistry.prototype);
                globalThis.customElements = registry;

                delete globalThis.__broilerConstructCustomElement;
                delete globalThis.__broilerCustomElementRegistry;
            })();
            """,
            "broiler:custom-elements");

        realm.DefineValue(JsInterop.FromEngineObject(window), "customElements", registry);
        SubscribeCustomElementReactions();
    }

    /// <summary>
    /// Turns the canonical mutation stream into reaction callbacks.
    /// </summary>
    /// <remarks>
    /// <c>DomDocument.Mutated</c> is raised synchronously at mutation time, which is what this needs:
    /// a browser runs <c>connectedCallback</c> before the statement after the <c>appendChild</c> that
    /// caused it. Building reactions on <c>MutationObserver</c> instead — the obvious reuse, since it
    /// already subscribes here — would have delivered every one of them a microtask late, and a
    /// component that reads its own DOM straight after inserting itself would have seen nothing.
    /// </remarks>
    private void SubscribeCustomElementReactions()
    {
        if (_customElementReactionsSubscribed)
            return;

        _customElementReactionsSubscribed = true;
        _document.Mutated += OnCustomElementRelevantMutation;
        foreach (var other in _browsingContextDocuments)
            other.Mutated += OnCustomElementRelevantMutation;
    }

    /// <summary>
    /// Subscribes a document this bridge minted for a detached browsing context, so a node adopted
    /// <em>into</em> it is heard.
    /// </summary>
    /// <remarks>
    /// Adoption publishes its record on the document the node is moving to, not the one it is leaving
    /// — so listening to the main document alone hears an adoption into the page and misses the
    /// symmetric one out of it. There is one registry across every document this bridge owns, so the
    /// same handler serves them all.
    /// </remarks>
    private void SubscribeBrowsingContextDocument(DomDocument document)
    {
        if (!_browsingContextDocuments.Add(document) || !_customElementReactionsSubscribed)
            return;

        document.Mutated += OnCustomElementRelevantMutation;
    }

    private readonly HashSet<DomDocument> _browsingContextDocuments = [];

    private bool _customElementReactionsSubscribed;

    private void OnCustomElementRelevantMutation(DomMutationRecord record)
    {
        if (_customElements is not { } registry)
            return;

        if (record.Type == DomMutationType.Adoption)
        {
            registry.OnAdoption(record.Target, DocumentValue(record.OldDocument), DocumentValue(record.NewDocument));
            return;
        }

        if (record.Type == DomMutationType.ChildList)
        {
            // Both lists are optional on the record, and a childList record normally carries only
            // one of them.
            registry.OnChildListMutation(
                record.AddedNodes ?? [],
                record.RemovedNodes ?? []);
            // A move changes a form-associated custom element's owner and can change its disabled
            // state (an ancestor fieldset), and both are computed from the tree rather than stored.
            registry.SyncFormState();
            return;
        }

        if (record.Type == DomMutationType.Attributes && record.Target is DomElement element &&
            record.AttributeName is { } attributeName)
        {
            registry.OnAttributeMutation(element, attributeName, record.OldValue);
            // `disabled`, `form` and `id` each move a form-associated custom element between states;
            // the sweep costs one pass over the elements a page actually upgraded.
            registry.SyncFormState();
        }
    }

    /// <summary>The JS object for a document node — the window's <c>document</c> for the page, its own
    /// wrapper for a document this bridge minted, and <c>null</c> for one that has neither.</summary>
    /// <remarks>
    /// The wrapper caches are still engine-typed, so each answer crosses through
    /// <see cref="JsInterop"/> — a cast, not a conversion, so the handle carries the object the page
    /// already holds and <c>evt.oldDocument === frameDoc</c> stays the question it was.
    /// </remarks>
    private JsValue DocumentValue(DomDocument? document)
    {
        if (document is null)
            return JsValue.Null;

        if (ReferenceEquals(document, _document))
            return _documentJSObject is { } main ? JsInterop.FromEngineObject(main) : JsValue.Null;

        return _jsObjects.TryGetDocument(document, out var wrapper) ? wrapper : JsValue.Null;
    }
}
