using System.Text.RegularExpressions;
using Broiler.Dom;
using Broiler.HtmlBridge.Jseal;
using Broiler.JavaScript.Runtime;

namespace Broiler.HtmlBridge.Dom.Features;

/// <summary>
/// Custom Elements (HTML §4.13) — the <c>customElements</c> registry, a constructible
/// <c>HTMLElement</c> base, and the reaction callbacks a definition receives.
/// </summary>
/// <remarks>
/// <para>
/// There was no production implementation at all: <c>customElements</c> was undefined and
/// <c>HTMLElement</c> threw <c>Illegal constructor</c>, so <c>class X extends HTMLElement</c>
/// followed by <c>customElements.define(…)</c> failed on the bare name and took the whole script
/// with it. The WPT runner carried a shim to get past that, which had to fake the parts it could not
/// reach — its <c>HTMLElement</c> handed back a plain element that did not carry the class's
/// prototype, so the shim copied the reaction callbacks across by hand and a component's own methods
/// were simply unreachable.
/// </para>
/// <para>
/// <b>Why the base constructor is JavaScript and everything else is not.</b> Constructing a custom
/// element is the one step that needs <c>new.target</c>: <c>new X()</c> runs <c>X</c>'s constructor,
/// which calls <c>super()</c>, and only <c>new.target</c> says which subclass is being built and so
/// which prototype and tag name the element must get. The base lives in JavaScript and calls back
/// here for the element itself; everything else (the registry, name validation, upgrades, reaction
/// dispatch) is C#, where the DOM is.
/// </para>
/// <para>
/// <b>The base still smuggles <c>new.target</c> through as argument zero, and that is now a choice
/// rather than a limitation.</b> <see cref="JsCall.NewTarget"/> exists and the Broiler.JS provider
/// populates it correctly for a host constructor, so <see cref="ConstructForNewTarget"/> could read
/// it directly. It does not, because it is not only the <c>HTMLElement</c> base below that calls it:
/// every per-tag interface constructor does too — <c>class Fancy extends HTMLButtonElement</c> reaches
/// this same host function through <c>HTMLButtonElement</c> — and those are generated by
/// <c>DomBridge/Utilities.DomInterfaces.cs</c>, which passes <c>(new.target, interfaceName)</c> in
/// exactly this shape. Reading <c>new.target</c> from the call frame would answer the wrong thing for
/// all of them: the frame belongs to the <em>host function being called from JavaScript</em>, which is
/// an ordinary call, not the <c>new</c> that started it. Both halves have to move together or neither
/// does, so the shape is preserved and the argument is read where it always was.
/// </para>
/// <para>
/// <b>Upgrading reuses the same constructor path rather than a second one</b>, which is what the
/// specification's "custom element construction stack" is for. Upgrading pushes the existing element
/// onto <see cref="_constructionStack"/> and calls the definition's constructor; the base's callback
/// finds a pending element and hands that one back instead of minting a new one, so the author's
/// constructor body runs against the element already in the tree. Without it an upgrade would have
/// to copy attributes and children onto a fresh element and swap it in — which is what the shim did,
/// and it loses node identity: a page holding a reference to the element before the definition
/// landed would keep pointing at the discarded one.
/// </para>
/// <para>
/// Reactions are dispatched off the canonical <c>DomDocument.Mutated</c> stream, which is raised
/// synchronously at mutation time. That matters: a browser runs <c>connectedCallback</c> before the
/// statement after <c>appendChild</c>, so building this on <c>MutationObserver</c> — whose delivery
/// is a microtask — would have put every reaction one checkpoint late.
/// </para>
/// <para>
/// <b>Customized built-ins and <c>adoptedCallback</c> are in.</b> A definition may name the built-in
/// it extends, and an element then has an <em>is value</em> as well as a local name — which is what
/// <see cref="_isValues"/> holds and what <see cref="DefinitionFor"/> matches on. The is value is not
/// the <c>is</c> content attribute: an element parsed from <c>&lt;button is="fancy-b"&gt;</c> has
/// both, but <c>new FancyButton()</c> and <c>createElement('button', {is: 'fancy-b'})</c> produce an
/// element whose <c>getAttribute('is')</c> is <see langword="null"/> while it still serializes as
/// <c>&lt;button is="fancy-b"&gt;</c>. Measured against Chromium, both halves.
/// </para>
/// <para>
/// The JavaScript vocabulary is JSEAL's (<see cref="IJsRealm"/>). One member stays engine-typed and
/// is pinned from outside: <see cref="CreateDefined"/>, whose caller
/// <c>DomBridge/DomBridge.DocumentFactoryHost.cs</c> implements an <c>IDocumentFactoryHost</c> that
/// still declares an engine return type. It forwards to <see cref="CreateDefinedElement"/> through
/// <see cref="Runtime.JsInterop"/> — a cast, not a conversion — and goes when that contract migrates.
/// </para>
/// </remarks>
internal sealed partial class CustomElementsBinding(ICustomElementsHost host)
{
    private readonly ICustomElementsHost _host = host;

    /// <summary>The definitions, by tag name.</summary>
    private readonly Dictionary<string, CustomElementDefinition> _byName = new(StringComparer.Ordinal);

    /// <summary>The same definitions by constructor, so <c>getName</c> and the base's callback can
    /// go the other way. One constructor may define only one element (HTML §4.13.4).</summary>
    /// <remarks>
    /// Keyed on the handle rather than on the engine object behind it, which is the same question:
    /// <see cref="JsValue"/>'s equality is reference equality for anything the engine owns, so two
    /// handles over one constructor are one key.
    /// </remarks>
    private readonly Dictionary<JsValue, CustomElementDefinition> _byConstructor = [];

    /// <summary>
    /// The elements currently being upgraded, innermost last — the specification's custom element
    /// construction stack. Non-empty exactly while a definition's constructor is running for an
    /// element that already exists.
    /// </summary>
    private readonly List<DomElement> _constructionStack = [];

    /// <summary>
    /// <c>whenDefined</c> resolvers waiting on a name that is not defined yet — the realm's own
    /// settle functions, held directly rather than wrapped in a function object no page can reach.
    /// </summary>
    private readonly Dictionary<string, List<Action<JsValue>>> _whenDefined = new(StringComparer.Ordinal);

    /// <summary>
    /// The <em>is value</em> of an element that has one without carrying an <c>is</c> content
    /// attribute — what <c>new FancyButton()</c> and <c>createElement('button', {is: …})</c> produce.
    /// </summary>
    /// <remarks>
    /// Kept beside the registry rather than on the element, because it is only meaningful to the
    /// registry: it is what decides which definition an element belongs to, and it is the one piece
    /// of custom-element state a content attribute cannot always carry. An element parsed with
    /// <c>is="fancy-b"</c> is not in this table — its attribute is the is value — which is why
    /// <see cref="IsValueOf"/> reads both.
    /// </remarks>
    private readonly Dictionary<DomElement, string> _isValues = [];

    /// <summary>
    /// One definition. <paramref name="Name"/> is the custom element name the registry is keyed by;
    /// <paramref name="LocalName"/> is the tag an element of it actually has — the same string for an
    /// autonomous element, and the <c>extends</c> option's value for a customized built-in.
    /// </summary>
    private sealed record CustomElementDefinition(
        string Name,
        string LocalName,
        JsValue Constructor,
        HashSet<string> ObservedAttributes,
        bool HasAttributeChangedCallback,
        bool FormAssociated)
    {
        /// <summary>Whether this definition extends a built-in element rather than defining a new tag.</summary>
        public bool IsCustomizedBuiltIn => !string.Equals(Name, LocalName, StringComparison.Ordinal);
    }

    /// <summary>
    /// A valid custom element name (HTML §4.13.1): starts with an ASCII lower alpha, contains a
    /// hyphen, and holds no upper-case letters.
    /// </summary>
    /// <remarks>
    /// The reserved names below are the SVG and MathML element names that already contain a hyphen,
    /// so they would otherwise pass the shape test while naming something that exists. Measured
    /// against a browser rather than transcribed: each is a <c>SyntaxError</c>, as is a name with no
    /// hyphen, an empty name, one with an upper-case letter, and one starting with a digit.
    /// </remarks>
    [GeneratedRegex(@"^[a-z][-._0-9a-z]*-[-._0-9a-z]*$", RegexOptions.Compiled)]
    private static partial System.Text.RegularExpressions.Regex ValidNamePattern();

    private static readonly HashSet<string> ReservedNames = new(StringComparer.Ordinal)
    {
        "annotation-xml", "color-profile", "font-face", "font-face-src", "font-face-uri",
        "font-face-format", "font-face-name", "missing-glyph",
    };

    internal static bool IsValidCustomElementName(string name) =>
        name.Length > 0 && !ReservedNames.Contains(name) && ValidNamePattern().IsMatch(name);

    /// <summary>Whether <paramref name="tagName"/> has a definition — used by the element-wrapper
    /// interface lookup so a defined element reports its own class.</summary>
    internal bool IsDefined(string tagName) => _byName.ContainsKey(tagName);

    /// <summary>Whether the element is a custom element — the gate <c>attachInternals</c> applies,
    /// which a browser refuses for an ordinary one.</summary>
    internal bool IsCustom(DomElement element) => _upgraded.Contains(element);

    /// <summary>Whether the element is an upgraded custom element whose definition declared
    /// <c>static formAssociated = true</c>.</summary>
    internal bool IsFormAssociated(DomElement element) =>
        _upgraded.Contains(element) && DefinitionFor(element) is { FormAssociated: true };

    /// <summary>
    /// The element's <em>is value</em>: the name of the definition it claims to belong to, or
    /// <see langword="null"/> for an ordinary element.
    /// </summary>
    /// <remarks>
    /// The internal value wins over the content attribute because it is the one an element created
    /// through <c>createElement(tag, {is})</c> or a constructor has, and such an element carries no
    /// <c>is</c> attribute at all. An element parsed from markup has only the attribute. Neither
    /// alone covers both shapes.
    /// </remarks>
    private string? IsValueOf(DomElement element) =>
        _isValues.TryGetValue(element, out var recorded) ? recorded
        : DomBridge.TryGetAttribute(element, "is", out var attribute) && attribute.Length > 0 ? attribute
        : null;

    /// <summary>
    /// Notes an element's is value. Called for an element created with an <c>is</c> option whose name
    /// is not defined yet — the value has to survive so a later <c>define</c> can upgrade it, and so
    /// serialization can report it.
    /// </summary>
    internal void RecordIsValue(DomElement element, string isValue) => _isValues[element] = isValue;

    /// <summary>The is value serialization should report for <paramref name="element"/>, or
    /// <see langword="null"/> when the element has none of its own.</summary>
    internal string? SerializedIsValue(DomElement element) =>
        _isValues.TryGetValue(element, out var recorded) ? recorded : null;

    /// <summary>
    /// The definition <paramref name="element"/> belongs to, or <see langword="null"/>.
    /// </summary>
    /// <remarks>
    /// An is value is authoritative when there is one: it selects the definition, and the definition
    /// only applies if its local name is the element's tag. That last test is what keeps
    /// <c>&lt;div is="fancy-b"&gt;</c> an ordinary <c>&lt;div&gt;</c> — measured, a browser leaves it
    /// alone rather than upgrading it against the wrong interface. With no is value the element can
    /// only be an autonomous custom element, which is why a customized-built-in definition is
    /// excluded here: <c>&lt;button&gt;</c> with a <c>button</c>-extending definition in the registry
    /// is still a plain button.
    /// </remarks>
    private CustomElementDefinition? DefinitionFor(DomElement element)
    {
        var tag = DomBridge.AsciiToLower(element.TagName);
        if (IsValueOf(element) is { } isValue)
        {
            return _byName.TryGetValue(isValue, out var customized) &&
                   string.Equals(customized.LocalName, tag, StringComparison.Ordinal)
                ? customized
                : null;
        }

        return _byName.TryGetValue(tag, out var autonomous) && !autonomous.IsCustomizedBuiltIn
            ? autonomous
            : null;
    }

    // ---------------- registry ----------------

    /// <summary><c>customElements.define(name, constructor)</c>.</summary>
    internal JsValue Define(in JsCall call)
    {
        var realm = call.Realm;
        var name = call.Length > 0 ? realm.ToJsString(call[0]) : string.Empty;

        if (call.Length < 2 || !call[1].IsFunction)
        {
            throw realm.Error(
                JsErrorKind.TypeError,
                "Failed to execute 'define' on 'CustomElementRegistry': the constructor is not a constructor.");
        }

        var constructor = call[1];

        if (!IsValidCustomElementName(name))
        {
            throw realm.DomError(
                "SyntaxError",
                $"Failed to execute 'define' on 'CustomElementRegistry': '{name}' is not a valid custom element name.");
        }

        // The `extends` option names the built-in this definition customizes; absent, null or
        // undefined all mean an autonomous element whose local name is its own name.
        var localName = name;
        if (call.Length > 2 && call[2].IsObject &&
            realm.GetProperty(call[2], "extends") is { IsNullish: false } extends)
        {
            localName = ResolveExtends(realm, realm.ToJsString(extends));
        }

        if (_byName.ContainsKey(name))
        {
            throw realm.DomError(
                "NotSupportedError",
                $"Failed to execute 'define' on 'CustomElementRegistry': the name '{name}' has already been used.");
        }

        if (_byConstructor.ContainsKey(constructor))
        {
            throw realm.DomError(
                "NotSupportedError",
                "Failed to execute 'define' on 'CustomElementRegistry': this constructor has already been used.");
        }

        // The three reads below happen in this order because a definition's members may be page
        // getters, and Object.defineProperty(X, 'observedAttributes', {get(){…}}) can observe when it
        // was asked. It is the order the constructor-argument list used to impose.
        var observedAttributes = ReadObservedAttributes(realm, constructor);
        var prototype = realm.GetProperty(constructor, "prototype");
        var hasAttributeChangedCallback =
            prototype.IsObject && realm.GetProperty(prototype, "attributeChangedCallback").IsFunction;
        // formAssociated is read off the constructor, not the prototype: it is a static, and an
        // instance getter of the same name deliberately does not count — measured, a class
        // declaring `get formAssociated()` gets a NotSupportedError from attachInternals.
        var formAssociated = realm.GetProperty(constructor, "formAssociated").AsBoolean;

        var definition = new CustomElementDefinition(
            name,
            localName,
            constructor,
            observedAttributes,
            hasAttributeChangedCallback,
            formAssociated);

        _byName[name] = definition;
        _byConstructor[constructor] = definition;

        UpgradeDefined(definition);
        ResolveWhenDefined(name, constructor);
        return JsValue.Undefined;
    }

    /// <summary>
    /// Validates an <c>extends</c> option and yields the local name it names, throwing the specified
    /// failure otherwise.
    /// </summary>
    /// <remarks>
    /// Two rejections, and they are distinct rather than one "bad tag" case: a name that is itself a
    /// valid custom element name cannot be extended (a customized built-in customizes a
    /// <em>built-in</em>), and a name no HTML element has is an <c>HTMLUnknownElement</c>, which has
    /// no interface to extend either. Both messages are Chromium's, measured rather than invented —
    /// a page that logs the failure sees the same text it would in a browser.
    /// </remarks>
    private static string ResolveExtends(IJsRealm realm, string extendsName)
    {
        var localName = DomBridge.AsciiToLower(extendsName);

        if (IsValidCustomElementName(localName))
        {
            throw realm.DomError(
                "NotSupportedError",
                $"Failed to execute 'define' on 'CustomElementRegistry': \"{extendsName}\" is a valid custom element name");
        }

        if (DomBridge.HtmlInterfaceForTag(localName) == "HTMLUnknownElement")
        {
            throw realm.DomError(
                "NotSupportedError",
                $"Failed to execute 'define' on 'CustomElementRegistry': \"{extendsName}\" is an HTMLUnknownElement");
        }

        return localName;
    }

    /// <summary>
    /// The definition's <c>observedAttributes</c>, read once at definition time as the specification
    /// requires — a later change to the static getter does not retroactively widen what is observed.
    /// </summary>
    /// <remarks>
    /// Both reads are the observable ECMAScript coercions rather than handle inspections: the list is
    /// whatever the page's static getter answered, so its <c>length</c> may be a string and an entry
    /// may be an object with a <c>toString</c>. That is what a browser reads, and what a
    /// <c>ToNumber</c>/<c>ToString</c> on the handle alone would not.
    /// </remarks>
    private static HashSet<string> ReadObservedAttributes(IJsRealm realm, JsValue constructor)
    {
        var observed = new HashSet<string>(StringComparer.Ordinal);
        var list = realm.GetProperty(constructor, "observedAttributes");
        if (!list.IsObject)
            return observed;

        var length = (int)realm.ToNumber(realm.GetProperty(list, "length"));
        for (var index = 0; index < length; index++)
        {
            var entry = realm.GetIndex(list, (uint)index);
            if (!entry.IsNullish)
                observed.Add(realm.ToJsString(entry));
        }

        return observed;
    }

    internal JsValue Get(in JsCall call)
    {
        var name = call.Length > 0 ? call.Realm.ToJsString(call[0]) : string.Empty;
        return _byName.TryGetValue(name, out var definition) ? definition.Constructor : JsValue.Undefined;
    }

    internal JsValue GetName(in JsCall call) =>
        call.Length > 0 && call[0].IsObject && _byConstructor.TryGetValue(call[0], out var definition)
            ? JsValue.String(definition.Name)
            : JsValue.Null;

    /// <summary>
    /// <c>customElements.whenDefined(name)</c> — a real promise that resolves with the constructor,
    /// rejecting with a <c>SyntaxError</c> for an invalid name.
    /// </summary>
    /// <remarks>
    /// The realm hands the promise and its two settle functions back rather than taking an executor,
    /// so a promise that is already settled is settled here and a pending one keeps its resolver as a
    /// delegate. The rejection value is a string rather than an <c>Error</c>, unchanged: that is what
    /// this operation has always rejected with.
    /// </remarks>
    internal JsValue WhenDefined(in JsCall call)
    {
        var realm = call.Realm;
        var name = call.Length > 0 ? realm.ToJsString(call[0]) : string.Empty;
        if (!IsValidCustomElementName(name))
        {
            var rejected = realm.NewPromise(out _, out var reject);
            reject(JsValue.String($"SyntaxError: '{name}' is not a valid custom element name."));
            return rejected;
        }

        if (_byName.TryGetValue(name, out var defined))
        {
            var already = realm.NewPromise(out var settle, out _);
            settle(defined.Constructor);
            return already;
        }

        var promise = realm.NewPromise(out var resolve, out _);
        if (!_whenDefined.TryGetValue(name, out var waiting))
            _whenDefined[name] = waiting = [];
        waiting.Add(resolve);
        return promise;
    }

    private void ResolveWhenDefined(string name, JsValue constructor)
    {
        if (!_whenDefined.Remove(name, out var waiting))
            return;

        foreach (var resolve in waiting)
            resolve(constructor);
    }

    /// <summary><c>customElements.upgrade(root)</c> — upgrades the shadow-including inclusive
    /// descendants of argument zero that have a definition and are not upgraded yet.</summary>
    internal JsValue Upgrade(in JsCall call)
    {
        if (call.Length == 0 || !call[0].IsObject || _host.FindNode(call[0]) is not { } root)
            return JsValue.Undefined;

        foreach (var element in InclusiveElements(root))
        {
            if (DefinitionFor(element) is { } definition)
                TryUpgrade(element, definition);
        }

        return JsValue.Undefined;
    }

    // ---------------- construction and upgrade ----------------

    /// <summary>
    /// The host half of the JavaScript <c>HTMLElement</c> base: given the <c>new.target</c> the base
    /// read, hands back the element the constructor should become.
    /// </summary>
    /// <remarks>
    /// <para>
    /// An element already being upgraded is returned as it is — that is the construction stack, and
    /// it is what lets an upgrade run the author's constructor against the node already in the tree
    /// rather than a replacement. Otherwise a fresh element is minted for the definition's
    /// <em>local</em> name, which is the extended tag for a customized built-in.
    /// </para>
    /// <para>
    /// Argument zero is the <c>new.target</c> its JavaScript caller read; see the class remarks for
    /// why it is passed rather than taken from <see cref="JsCall.NewTarget"/>, which for this call
    /// frame would describe the ordinary call the base makes and not the <c>new</c> that began it.
    /// </para>
    /// <para>
    /// Argument one is the interface whose constructor is running — HTML §4.13.3's "active function
    /// object", and the reason it has to be passed rather than inferred. The base a class extends must
    /// be the one its definition names: <c>class X extends HTMLButtonElement</c> registered without an
    /// <c>extends</c> option is a <c>TypeError</c>, and so is an <c>HTMLElement</c> subclass registered
    /// with one. Without the active interface both would silently construct the wrong element — an
    /// autonomous <c>&lt;x-thing&gt;</c> reached through <c>HTMLButtonElement</c>, which a browser
    /// refuses.
    /// </para>
    /// <para>
    /// A refusal is returned as a string, not thrown: the JavaScript base turns it into a real
    /// <c>TypeError</c> carrying that message, where a host throw would surface without the base's
    /// framing. <see cref="JsValue.Null"/> means the generic "Illegal constructor" — a
    /// <c>new.target</c> with no definition, and a bare <c>new HTMLElement()</c> with no
    /// <c>new.target</c> at all.
    /// </para>
    /// </remarks>
    internal JsValue ConstructForNewTarget(in JsCall call)
    {
        if (call.Length == 0 || !call[0].IsObject ||
            !_byConstructor.TryGetValue(call[0], out var definition))
            return JsValue.Null;

        var activeInterface = call.Length > 1 ? call.Realm.ToJsString(call[1]) : "HTMLElement";
        var requiredInterface = definition.IsCustomizedBuiltIn
            ? DomBridge.HtmlInterfaceForTag(definition.LocalName)
            : "HTMLElement";

        if (!string.Equals(activeInterface, requiredInterface, StringComparison.Ordinal))
        {
            return JsValue.String($"Failed to construct '{activeInterface}': Illegal constructor: " +
                (definition.IsCustomizedBuiltIn
                    ? "localName does not match the HTML element interface"
                    : "autonomous custom elements must extend HTMLElement"));
        }

        if (_constructionStack.Count > 0)
        {
            var pending = _constructionStack[^1];
            _constructionStack.RemoveAt(_constructionStack.Count - 1);
            return _host.WrapNode(pending);
        }

        var created = _host.CreateBridgeElement(definition.LocalName);
        if (definition.IsCustomizedBuiltIn)
        {
            // The is value, not an `is` attribute: a constructed customized built-in reports
            // getAttribute('is') as null while still serializing as <button is="…">. Measured.
            _isValues[created] = definition.Name;
        }

        // A constructed element is upgraded by definition — it was built from its own class. Marking
        // it here is what makes its reactions fire: without it a `document.createElement('x-thing')`
        // instance took no attributeChangedCallback, because the reaction dispatch only knows about
        // elements that went through an upgrade.
        _upgraded.Add(created);
        return _host.WrapNode(created);
    }

    /// <summary>
    /// Engine-typed adapter for <c>DomBridge/DomBridge.DocumentFactoryHost.cs</c>, whose
    /// <c>IDocumentFactoryHost</c> still hands the created element back as an engine object. See the
    /// remarks on this class.
    /// </summary>
    internal JSObject? CreateDefined(string tagName, string? isValue) =>
        CreateDefinedElement(tagName, isValue) is { IsObject: true } created
            ? Runtime.JsInterop.ToEngineObject(created)
            : null;

    /// <summary>
    /// Creates an element for a defined custom tag by running its constructor, which is what makes
    /// <c>document.createElement('x-thing')</c> hand back an instance of the class rather than a
    /// plain element. <paramref name="isValue"/> is <c>createElement</c>'s <c>is</c> option, which
    /// selects a customized built-in. Returns <see cref="JsValue.Missing"/> when nothing matches, so
    /// the ordinary path takes over.
    /// </summary>
    internal JsValue CreateDefinedElement(string tagName, string? isValue)
    {
        var lookup = isValue ?? tagName;
        if (!_byName.TryGetValue(lookup, out var definition) ||
            !string.Equals(definition.LocalName, tagName, StringComparison.Ordinal) ||
            (isValue is null && definition.IsCustomizedBuiltIn))
            return JsValue.Missing;

        var created = _host.Realm.Construct(definition.Constructor);
        return created.IsObject ? created : JsValue.Missing;
    }

    /// <summary>Upgrades every element in the document that this definition now names, in tree
    /// order — the elements a page parsed before the definition landed.</summary>
    private void UpgradeDefined(CustomElementDefinition definition)
    {
        foreach (var element in _host.Elements)
        {
            if (ReferenceEquals(DefinitionFor(element), definition))
                TryUpgrade(element, definition);
        }
    }

    /// <summary>The elements already marked as upgraded, so an element is never upgraded twice.</summary>
    private readonly HashSet<DomElement> _upgraded = [];

    /// <summary>
    /// Runs <paramref name="definition"/>'s constructor against <paramref name="element"/>, then the
    /// reactions the specification enqueues for an upgrade: <c>attributeChangedCallback</c> for each
    /// observed attribute it already carries, and <c>connectedCallback</c> when it is in the tree.
    /// </summary>
    /// <remarks>
    /// The attribute callbacks come before the connected one and report an <c>oldValue</c> of
    /// <see langword="null"/> — the element is only now becoming a custom element, so from the
    /// definition's point of view every attribute it already has is being set for the first time.
    /// Measured.
    /// </remarks>
    private void TryUpgrade(DomElement element, CustomElementDefinition definition)
    {
        if (!_upgraded.Add(element))
            return;

        _constructionStack.Add(element);
        try
        {
            _host.Realm.Construct(definition.Constructor);
        }
        catch (Exception)
        {
            // A constructor that throws leaves the element un-upgraded rather than taking the
            // define() call down with it — one bad definition must not stop the others.
            _upgraded.Remove(element);
            return;
        }
        finally
        {
            if (_constructionStack.Count > 0 && ReferenceEquals(_constructionStack[^1], element))
                _constructionStack.RemoveAt(_constructionStack.Count - 1);
        }

        foreach (var attributeName in DomBridge.AttributeNames(element).ToList())
        {
            if (definition.ObservedAttributes.Contains(attributeName) &&
                DomBridge.TryGetAttribute(element, attributeName, out var value))
            {
                InvokeReaction(element, "attributeChangedCallback",
                    JsValue.String(attributeName), JsValue.Null, JsValue.String(value));
            }
        }

        if (definition.FormAssociated)
        {
            // The form-association reaction comes before the connected one and is not conditional on
            // being connected: an upgrade inside a form reports that form, and one outside any form
            // reports null only once something moves it. Tracked from here so the first observation
            // is the upgrade itself rather than a later mutation.
            _formAssociated.Add(element);
            _formOwners[element] = _host.FormOwnerOf(element);
            _disabled[element] = _host.IsFormControlDisabled(element);
            if (_formOwners[element] is { } owner)
                InvokeReaction(element, "formAssociatedCallback", _host.WrapNode(owner));
        }

        if (_host.IsConnected(element))
            InvokeReaction(element, "connectedCallback");
    }

    /// <summary>The upgraded form-associated custom elements, and the two pieces of state whose
    /// changes they are told about.</summary>
    private readonly HashSet<DomElement> _formAssociated = [];
    private readonly Dictionary<DomElement, DomElement?> _formOwners = [];
    private readonly Dictionary<DomElement, bool> _disabled = [];

    /// <summary>
    /// Re-reads every form-associated custom element's owner and disabled state and reports what
    /// changed. Called after each mutation, because both are computed from the tree rather than
    /// stored: a form owner changes when the element moves, when its <c>form</c> attribute changes,
    /// and when the form it names appears; a disabled state changes with its own attribute and with
    /// any ancestor <c>&lt;fieldset&gt;</c>'s.
    /// </summary>
    /// <remarks>
    /// Sweeping rather than deriving which element a given mutation could have affected: the set is
    /// only the form-associated custom elements a page has actually upgraded, and the alternatives —
    /// mapping a fieldset mutation to its descendants, an id change to the elements naming it — are
    /// the kind of partial dependency tracking that silently misses a case.
    /// </remarks>
    internal void SyncFormState()
    {
        if (_formAssociated.Count == 0)
            return;

        foreach (var element in _formAssociated.ToList())
        {
            var owner = _host.FormOwnerOf(element);
            if (!_formOwners.TryGetValue(element, out var previousOwner) || !ReferenceEquals(previousOwner, owner))
            {
                _formOwners[element] = owner;
                InvokeReaction(element, "formAssociatedCallback",
                    owner is null ? JsValue.Null : _host.WrapNode(owner));
            }

            var disabled = _host.IsFormControlDisabled(element);
            if (!_disabled.TryGetValue(element, out var previousDisabled) || previousDisabled != disabled)
            {
                _disabled[element] = disabled;
                InvokeReaction(element, "formDisabledCallback", JsValue.Boolean(disabled));
            }
        }
    }

    /// <summary>
    /// Reports a form reset to the form-associated custom elements among
    /// <paramref name="controls"/> — the reaction a component resets its own value in.
    /// </summary>
    /// <remarks>
    /// <c>formStateRestoreCallback</c> has no equivalent hook and is deliberately never fired: it
    /// reports a value restored by session history or an autofill pass, and this engine performs
    /// neither, so firing it would be an invention rather than a restoration.
    /// </remarks>
    internal void OnFormReset(IReadOnlyList<DomElement> controls)
    {
        foreach (var control in controls)
        {
            if (_formAssociated.Contains(control))
                InvokeReaction(control, "formResetCallback");
        }
    }

    // ---------------- reactions ----------------

    /// <summary>Runs a reaction callback on an upgraded element, if its class declares one.</summary>
    /// <remarks>
    /// Looked up on the element itself rather than on the definition's prototype: the element's
    /// prototype <em>is</em> the class's after an upgrade, so this finds an override on the instance
    /// and an inherited callback alike, and calls it with <c>this</c> bound to the element the way
    /// the author wrote it expecting.
    /// </remarks>
    private void InvokeReaction(DomElement element, string callback, params JsValue[] arguments)
    {
        if (!_upgraded.Contains(element) || !_host.TryGetWrapper(element, out var wrapper))
            return;

        var realm = _host.Realm;
        var reaction = realm.GetProperty(wrapper, callback);
        if (!reaction.IsFunction)
            return;

        try
        {
            realm.Invoke(reaction, wrapper, arguments);
        }
        catch (Exception)
        {
            // A throwing reaction is reported to the page's error handling, not propagated into the
            // DOM operation that triggered it — an appendChild must not fail because a component's
            // connectedCallback did.
        }
    }

    /// <summary>Dispatches the connected/disconnected reactions for a tree mutation.</summary>
    internal void OnChildListMutation(IReadOnlyList<DomNode> added, IReadOnlyList<DomNode> removed)
    {
        foreach (var node in removed)
        {
            foreach (var element in InclusiveElements(node))
                InvokeReaction(element, "disconnectedCallback");
        }

        foreach (var node in added)
        {
            foreach (var element in InclusiveElements(node))
            {
                // An element inserted with a definition already in place becomes a custom element
                // now — the shape a page produces with `innerHTML` or by appending parsed markup
                // after its component script ran. Upgrading dispatches the connected reaction itself,
                // so it must not be dispatched twice.
                if (!_upgraded.Contains(element) && DefinitionFor(element) is { } definition)
                {
                    TryUpgrade(element, definition);
                    continue;
                }

                if (_host.IsConnected(element))
                    InvokeReaction(element, "connectedCallback");
            }
        }
    }

    /// <summary>Dispatches <c>attributeChangedCallback</c> for an observed attribute.</summary>
    internal void OnAttributeMutation(DomElement element, string attributeName, string? oldValue)
    {
        if (!_upgraded.Contains(element) ||
            DefinitionFor(element) is not { } definition ||
            !definition.ObservedAttributes.Contains(attributeName))
            return;

        // JsValue.String maps a CLR null onto JavaScript null, which is exactly what an absent
        // attribute reports here — so the removal case needs no arm of its own.
        var newValue = DomBridge.TryGetAttribute(element, attributeName, out var current)
            ? JsValue.String(current)
            : JsValue.Null;

        InvokeReaction(element, "attributeChangedCallback",
            JsValue.String(attributeName),
            oldValue is null ? JsValue.Null : JsValue.String(oldValue),
            newValue);
    }

    /// <summary>
    /// Dispatches <c>adoptedCallback(oldDocument, newDocument)</c> for a node that changed document.
    /// </summary>
    /// <remarks>
    /// The whole adopted subtree receives it, not only the node named on the record: adoption moves
    /// every descendant's node document, so every upgraded custom element in it has changed document
    /// too. The removal from the old tree that adoption performs first is an ordinary child-list
    /// mutation, so <c>disconnectedCallback</c> has already run by the time this does — which is the
    /// order a browser produces and is measured rather than assumed.
    /// </remarks>
    internal void OnAdoption(DomNode node, JsValue oldDocument, JsValue newDocument)
    {
        foreach (var element in InclusiveElements(node))
            InvokeReaction(element, "adoptedCallback", oldDocument, newDocument);
    }

    private static IEnumerable<DomElement> InclusiveElements(DomNode node) =>
        node.InclusiveDescendants().OfType<DomElement>();
}
